# Copyright (c) 2015-2016, NVIDIA CORPORATION.  All rights reserved.

sudo: required
dist: trusty

language: python
python:
    2.7
compiler: gcc
env:
    global:
        - NUM_THREADS=4
    matrix:
        - CAFFE_FORK=NVIDIA
        - CAFFE_FORK=BVLC

cache:
    apt: true
    directories:
        - ~/caffe
        - ~/torch

addons:
    apt:
        packages:
            - build-essential
            - cmake
            - cython
            - git
            - gfortran
            - graphviz
            - libboost-filesystem-dev
            - libboost-python-dev
            - libboost-system-dev
            - libboost-thread-dev
            - libgflags-dev
            - libgoogle-glog-dev
            - libhdf5-serial-dev
            - libleveldb-dev
            - liblmdb-dev
            - libopenblas-dev
            - libopencv-dev
            - libprotobuf-dev
            - libsnappy-dev
            - protobuf-compiler
            - python-dev
            - python-flask
            - python-gevent
            - python-gevent-websocket
            - python-gflags
            - python-h5py
            - python-matplotlib
            - python-mock
            - python-nose
            - python-numpy
            - python-pil
            - python-pip
            - python-protobuf
            - python-psutil
            - python-requests
            - python-scipy
            - python-six
            - python-skimage


before_install:
    # undo all of TravisCI's "helpful" Python shenanigans on 14.04
    - deactivate
    # use --system-site-packages so that Python will use deb packages
    - virtualenv --system-site-packages ~/venv
    - source ~/venv/bin/activate
    - which python
    - python --version
    - which pip
    - pip --version

install:
    # bust build caches
    - ./scripts/travis/bust-cache.sh ~/caffe ~/torch

    # build caffe
    - ./scripts/travis/install-caffe.sh ~/caffe

    # build torch
    - travis_wait ./scripts/travis/install-torch-wrapper.sh ~/torch $(pwd)/torch-install-log.txt

    # digits requirements
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt

    # image gradients plug-ins
    - pip install -e .
    - pip install plugins/data/imageGradients
    - pip install plugins/view/imageGradients

before_script:
    - export CAFFE_ROOT=~/caffe
    - export TORCH_ROOT=~/torch
    # Disable OpenMP multi-threading
    - export OMP_NUM_THREADS=1

script:
    ./digits-test -v --with-coverage --cover-package=digits

after_success:
    coveralls

